### PR TITLE
Release v0.12.0?

### PR DESCRIPTION
**Pull request by michaelkirk**
I've drafted up some release notes.

We still have a couple nearly-merged PR's that would be good to include.

#188, #189, #190

What do people think?

### CODE REVIEW

**Comment by kylebarron** [comment]
I'm happy to get more of my PRs resolved before the 0.12 release, but I need some more feedback. I don't know what the appetite for breaking changes is, but if there isn't much appetite for breaking changes, then https://github.com/georust/geozero/issues/184 can be closed and https://github.com/georust/geozero/pull/183 might be able to be finished

**Comment by michaelkirk** [comment]
> I don't know what the appetite for breaking changes is, but if there isn't much appetite for breaking changes, then https://github.com/georust/geozero/issues/184 can be closed

I hit the same confusion: https://github.com/michaelkirk/geomedea/blob/main/geomedea_geozero/src/geozero_reader.rs#L92

I think I'm in favor of the change - in my experience, the existing behavior is surprising and leads to bugs. Part of making that change would be updating all the formats in this repo and ideally notifying any others that we know of.

That said, there's no reason I know of that it has to happen in this release.

re: #183 - I'll review shortly.

**Comment by kylebarron** [comment]
> I hit the same confusion: https://github.com/michaelkirk/geomedea/blob/main/geomedea_geozero/src/geozero_reader.rs#L92

😅 

> I think I'm in favor of the change - in my experience, the existing behavior is surprising and leads to bugs. Part of making that change would be updating all the formats in this repo and ideally notifying any others that we know of.
> 
> That said, there's no reason I know of that it has to happen in this release.

I agree that I'm in favor of the change, agree that it's a bigger lift because you have to ensure writers are up to date, and agree it doesn't need to happen in this release.

**Comment by kylebarron** [comment]
Once we have #186 merged, I'd love to get an 0.12 release out! Let me know if I can help with this at all

**Comment by kylebarron** [comment]
I created #196 with an updated changelog from some of my recent PRs. Feel free to merge those changes back in here if you'd prefer.

**Comment by michaelkirk** [comment]
superseded by #196

**Pull request closed without merging**
